spring.application.name=tracker
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-da5h7r3m8hqs73cmqco0-a/tracker_rj3x
spring.datasource.username=postgre
spring.datasource.password=BJEAhT3Qgkv1X5vhmyRRXs0qfvGbE5ld

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
